[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown",
    "armv7-unknown-linux-gnueabihf",
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "aarch64-apple-ios",
    "x86_64-apple-ios",
]
all-features = true

[advisories]
ignore = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
deny = [
    { crate = "openssl", use-instead = "rustls" },
    { crate = "openssl-sys", use-instead = "rustls" },
]
skip = [
    { name = "getrandom", version = "0.2.15" },
]
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "BSD-2-Clause",
    "MIT-0",
]
unused-allowed-license = "warn"
