name: Audit

permissions:
  contents: read

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with: { submodules: recursive }
      - uses: taiki-e/install-action@25f25a6eff908c77b40880d0b1f5d2a032b6e75a
        with: { tool: cargo-deny }
      - uses: taiki-e/install-action@25f25a6eff908c77b40880d0b1f5d2a032b6e75a
        with: { tool: cargo-audit }
      - run: cargo deny check advisories
      - run: cargo audit
